/* conf */
INSERT INTO mongo (
    entity,
    type,
    language,
    datatype,
    value_string,
    value_integer,
    value_reference
) VALUES
    ('database', '_mid', NULL, 'string', 'database', NULL, NULL),
    ('database', '_type', NULL, 'reference', NULL, NULL, 'entity'),
    ('database', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database', 'name', NULL, 'string', 'database', NULL, NULL),
    ('database', 'label', 'en', 'string', 'Database', NULL, NULL),
    ('database', 'label', 'et', 'string', 'Andmebaas', NULL, NULL),
    ('database', 'label_plural', 'en', 'string', 'Databases', NULL, NULL),
    ('database', 'label_plural', 'et', 'string', 'Andmebaasid', NULL, NULL),
    ('database', 'system', NULL, 'boolean', NULL, 1, NULL),

    ('database_name', '_mid', NULL, 'string', 'database_name', NULL, NULL),
    ('database_name', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('database_name', '_parent', NULL, 'reference', NULL, NULL, 'database'),
    ('database_name', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database_name', 'name', NULL, 'string', 'name', NULL, NULL),
    ('database_name', 'label', 'en', 'string', 'Name', NULL, NULL),
    ('database_name', 'label', 'et', 'string', 'Nimi', NULL, NULL),
    ('database_name', 'type', NULL, 'string', 'string', NULL, NULL),
    ('database_name', 'ordinal', NULL, 'integer', NULL, 1, NULL),
    ('database_name', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('database_name', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('database_name', 'readonly', NULL, 'boolean', NULL, 1, NULL),
    ('database_name', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('database_organization', '_mid', NULL, 'string', 'database_organization', NULL, NULL),
    ('database_organization', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('database_organization', '_parent', NULL, 'reference', NULL, NULL, 'database'),
    ('database_organization', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database_organization', 'name', NULL, 'string', 'organization', NULL, NULL),
    ('database_organization', 'label', 'en', 'string', 'Organization', NULL, NULL),
    ('database_organization', 'label', 'et', 'string', 'Asutus', NULL, NULL),
    ('database_organization', 'type', NULL, 'string', 'string', NULL, NULL),
    ('database_organization', 'ordinal', NULL, 'integer', NULL, 2, NULL),
    ('database_organization', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('database_organization', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('database_organization', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('database_address', '_mid', NULL, 'string', 'database_address', NULL, NULL),
    ('database_address', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('database_address', '_parent', NULL, 'reference', NULL, NULL, 'database'),
    ('database_address', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database_address', 'name', NULL, 'string', 'address', NULL, NULL),
    ('database_address', 'label', 'en', 'string', 'Address', NULL, NULL),
    ('database_address', 'label', 'et', 'string', 'Aadress', NULL, NULL),
    ('database_address', 'type', NULL, 'string', 'string', NULL, NULL),
    ('database_address', 'ordinal', NULL, 'integer', NULL, 3, NULL),
    ('database_address', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('database_email', '_mid', NULL, 'string', 'database_email', NULL, NULL),
    ('database_email', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('database_email', '_parent', NULL, 'reference', NULL, NULL, 'database'),
    ('database_email', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database_email', 'name', NULL, 'string', 'email', NULL, NULL),
    ('database_email', 'label', 'en', 'string', 'E-Mail', NULL, NULL),
    ('database_email', 'label', 'et', 'string', 'E-post', NULL, NULL),
    ('database_email', 'type', NULL, 'string', 'string', NULL, NULL),
    ('database_email', 'ordinal', NULL, 'integer', NULL, 4, NULL),
    ('database_email', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('database_photo', '_mid', NULL, 'string', 'database_photo', NULL, NULL),
    ('database_photo', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('database_photo', '_parent', NULL, 'reference', NULL, NULL, 'database'),
    ('database_photo', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database_photo', 'name', NULL, 'string', 'photo', NULL, NULL),
    ('database_photo', 'label', 'en', 'string', 'logo', NULL, NULL),
    ('database_photo', 'label', 'et', 'string', 'Logo', NULL, NULL),
    ('database_photo', 'type', NULL, 'string', 'file', NULL, NULL),
    ('database_photo', 'ordinal', NULL, 'integer', NULL, 5, NULL),
    ('database_photo', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('database_add_user', '_mid', NULL, 'string', 'database_add_user', NULL, NULL),
    ('database_add_user', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('database_add_user', '_parent', NULL, 'reference', NULL, NULL, 'database'),
    ('database_add_user', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database_add_user', 'name', NULL, 'string', 'add_user', NULL, NULL),
    ('database_add_user', 'label', 'en', 'string', 'Add new user', NULL, NULL),
    ('database_add_user', 'label', 'et', 'string', 'Lisa külastaja', NULL, NULL),
    ('database_add_user', 'description', 'en', 'string', 'When an unknown user logs in, a new user entity is automatically created under that entity. If you do not want to automatically create new users, leave this field blank. Then only manually added users can log in.', NULL, NULL),
    ('database_add_user', 'description', 'et', 'string', 'Kui tundmatu kasutaja logib sisse, luuakse selle objekti alla automaatselt uus kasutaja. Kui te ei soovi automaatselt uusi kasutajaid luua, jätke see väli tühjaks. Siis saavad sisse logida ainult käsitsi lisatud kasutajad.', NULL, NULL),
    ('database_add_user', 'type', NULL, 'string', 'reference', NULL, NULL),
    ('database_add_user', 'ordinal', NULL, 'integer', NULL, 6, NULL),
    ('database_add_user', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('database_billing_customer_id', '_mid', NULL, 'string', 'database_billing_customer_id', NULL, NULL),
    ('database_billing_customer_id', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('database_billing_customer_id', '_parent', NULL, 'reference', NULL, NULL, 'database'),
    ('database_billing_customer_id', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database_billing_customer_id', 'name', NULL, 'string', 'billing_customer_id', NULL, NULL),
    ('database_billing_customer_id', 'label', 'en', 'string', 'Customer Id', NULL, NULL),
    ('database_billing_customer_id', 'label', 'et', 'string', 'Kliendi tunnus', NULL, NULL),
    ('database_billing_customer_id', 'group', 'en', 'string', 'Billing', NULL, NULL),
    ('database_billing_customer_id', 'group', 'et', 'string', 'Arveldus', NULL, NULL),
    ('database_billing_customer_id', 'type', NULL, 'string', 'string', NULL, NULL),
    ('database_billing_customer_id', 'ordinal', NULL, 'integer', NULL, 10, NULL),
    ('database_billing_customer_id', 'readonly', NULL, 'boolean', NULL, 1, NULL),

    ('database_billing_entities_limit', '_mid', NULL, 'string', 'database_billing_entities_limit', NULL, NULL),
    ('database_billing_entities_limit', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('database_billing_entities_limit', '_parent', NULL, 'reference', NULL, NULL, 'database'),
    ('database_billing_entities_limit', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database_billing_entities_limit', 'name', NULL, 'string', 'billing_entities_limit', NULL, NULL),
    ('database_billing_entities_limit', 'label', 'en', 'string', 'Amount of entities', NULL, NULL),
    ('database_billing_entities_limit', 'label', 'et', 'string', 'Objektide kogus', NULL, NULL),
    ('database_billing_entities_limit', 'group', 'en', 'string', 'Billing', NULL, NULL),
    ('database_billing_entities_limit', 'group', 'et', 'string', 'Arveldus', NULL, NULL),
    ('database_billing_entities_limit', 'type', NULL, 'string', 'number', NULL, NULL),
    ('database_billing_entities_limit', 'ordinal', NULL, 'integer', NULL, 21, NULL),
    ('database_billing_entities_limit', 'readonly', NULL, 'boolean', NULL, 1, NULL),

    ('database_billing_data_limit', '_mid', NULL, 'string', 'database_billing_data_limit', NULL, NULL),
    ('database_billing_data_limit', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('database_billing_data_limit', '_parent', NULL, 'reference', NULL, NULL, 'database'),
    ('database_billing_data_limit', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database_billing_data_limit', 'name', NULL, 'string', 'billing_data_limit', NULL, NULL),
    ('database_billing_data_limit', 'label', 'en', 'string', 'Data size (GB)', NULL, NULL),
    ('database_billing_data_limit', 'label', 'et', 'string', 'Andmemaht (GB)', NULL, NULL),
    ('database_billing_data_limit', 'group', 'en', 'string', 'Billing', NULL, NULL),
    ('database_billing_data_limit', 'group', 'et', 'string', 'Arveldus', NULL, NULL),
    ('database_billing_data_limit', 'type', NULL, 'string', 'number', NULL, NULL),
    ('database_billing_data_limit', 'decimals', NULL, 'integer', NULL, 1, NULL),
    ('database_billing_data_limit', 'ordinal', NULL, 'integer', NULL, 22, NULL),
    ('database_billing_data_limit', 'readonly', NULL, 'boolean', NULL, 1, NULL),

    ('database_billing_requests_limit', '_mid', NULL, 'string', 'database_billing_requests_limit', NULL, NULL),
    ('database_billing_requests_limit', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('database_billing_requests_limit', '_parent', NULL, 'reference', NULL, NULL, 'database'),
    ('database_billing_requests_limit', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database_billing_requests_limit', 'name', NULL, 'string', 'billing_requests_limit', NULL, NULL),
    ('database_billing_requests_limit', 'label', 'en', 'string', 'Requests per month', NULL, NULL),
    ('database_billing_requests_limit', 'label', 'et', 'string', 'Päringute arv kuus', NULL, NULL),
    ('database_billing_requests_limit', 'group', 'en', 'string', 'Billing', NULL, NULL),
    ('database_billing_requests_limit', 'group', 'et', 'string', 'Arveldus', NULL, NULL),
    ('database_billing_requests_limit', 'type', NULL, 'string', 'number', NULL, NULL),
    ('database_billing_requests_limit', 'ordinal', NULL, 'integer', NULL, 23, NULL),
    ('database_billing_requests_limit', 'readonly', NULL, 'boolean', NULL, 1, NULL),

    ('database_billing_price', '_mid', NULL, 'string', 'database_billing_price', NULL, NULL),
    ('database_billing_price', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('database_billing_price', '_parent', NULL, 'reference', NULL, NULL, 'database'),
    ('database_billing_price', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('database_billing_price', 'name', NULL, 'string', 'price', NULL, NULL),
    ('database_billing_price', 'label', 'en', 'string', 'Price', NULL, NULL),
    ('database_billing_price', 'label', 'et', 'string', 'Hind', NULL, NULL),
    ('database_billing_price', 'group', 'en', 'string', 'Billing', NULL, NULL),
    ('database_billing_price', 'group', 'et', 'string', 'Arveldus', NULL, NULL),
    ('database_billing_price', 'type', NULL, 'string', 'number', NULL, NULL),
    ('database_billing_price', 'decimals', NULL, 'integer', NULL, 2, NULL),
    ('database_billing_price', 'ordinal', NULL, 'integer', NULL, 30, NULL),
    ('database_billing_price', 'readonly', NULL, 'boolean', NULL, 1, NULL),

    ('entity', '_mid', NULL, 'string', 'entity', NULL, NULL),
    ('entity', '_type', NULL, 'reference', NULL, NULL, 'entity'),
    ('entity', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('entity', 'name', NULL, 'string', 'entity', NULL, NULL),
    ('entity', 'label', 'en', 'string', 'Entity', NULL, NULL),
    ('entity', 'label', 'et', 'string', 'Objekt', NULL, NULL),
    ('entity', 'label_plural', 'en', 'string', 'Entities', NULL, NULL),
    ('entity', 'label_plural', 'et', 'string', 'Objektid', NULL, NULL),
    ('entity', 'add_from', NULL, 'reference', NULL, NULL, 'menu_conf_entity'),
    ('entity', 'default_parent', NULL, 'reference', NULL, NULL, CONCAT('database_entity_', ?)),
    ('entity', 'system', NULL, 'boolean', NULL, 1, NULL),

    ('entity_name', '_mid', NULL, 'string', 'entity_name', NULL, NULL),
    ('entity_name', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('entity_name', '_parent', NULL, 'reference', NULL, NULL, 'entity'),
    ('entity_name', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('entity_name', 'name', NULL, 'string', 'name', NULL, NULL),
    ('entity_name', 'label', 'en', 'string', 'Name', NULL, NULL),
    ('entity_name', 'label', 'et', 'string', 'Nimi', NULL, NULL),
    ('entity_name', 'type', NULL, 'string', 'string', NULL, NULL),
    ('entity_name', 'ordinal', NULL, 'integer', NULL, 10, NULL),
    ('entity_name', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('entity_name', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('entity_name', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('entity_label', '_mid', NULL, 'string', 'entity_label', NULL, NULL),
    ('entity_label', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('entity_label', '_parent', NULL, 'reference', NULL, NULL, 'entity'),
    ('entity_label', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('entity_label', 'name', NULL, 'string', 'label', NULL, NULL),
    ('entity_label', 'label', 'en', 'string', 'Label', NULL, NULL),
    ('entity_label', 'label', 'et', 'string', 'Silt', NULL, NULL),
    ('entity_label', 'type', NULL, 'string', 'string', NULL, NULL),
    ('entity_label', 'ordinal', NULL, 'integer', NULL, 20, NULL),
    ('entity_label', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('entity_label', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('entity_label', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('entity_label', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('entity_label_plural', '_mid', NULL, 'string', 'entity_label_plural', NULL, NULL),
    ('entity_label_plural', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('entity_label_plural', '_parent', NULL, 'reference', NULL, NULL, 'entity'),
    ('entity_label_plural', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('entity_label_plural', 'name', NULL, 'string', 'label_plural', NULL, NULL),
    ('entity_label_plural', 'label', 'en', 'string', 'Label (plural)', NULL, NULL),
    ('entity_label_plural', 'label', 'et', 'string', 'Silt (mitmuses)', NULL, NULL),
    ('entity_label_plural', 'type', NULL, 'string', 'string', NULL, NULL),
    ('entity_label_plural', 'ordinal', NULL, 'integer', NULL, 30, NULL),
    ('entity_label_plural', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('entity_label_plural', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('entity_label_plural', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('entity_description', '_mid', NULL, 'string', 'entity_description', NULL, NULL),
    ('entity_description', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('entity_description', '_parent', NULL, 'reference', NULL, NULL, 'entity'),
    ('entity_description', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('entity_description', 'name', NULL, 'string', 'description', NULL, NULL),
    ('entity_description', 'label', 'en', 'string', 'Description (help text)', NULL, NULL),
    ('entity_description', 'label', 'et', 'string', 'Kirjeldus (abi tekst)', NULL, NULL),
    ('entity_description', 'type', NULL, 'string', 'text', NULL, NULL),
    ('entity_description', 'ordinal', NULL, 'integer', NULL, 50, NULL),
    ('entity_description', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('entity_description', 'markdown', NULL, 'boolean', NULL, 1, NULL),
    ('entity_description', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('entity_add_from', '_mid', NULL, 'string', 'entity_add_from', NULL, NULL),
    ('entity_add_from', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('entity_add_from', '_parent', NULL, 'reference', NULL, NULL, 'entity'),
    ('entity_add_from', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('entity_add_from', 'name', NULL, 'string', 'add_from', NULL, NULL),
    ('entity_add_from', 'label', 'en', 'string', 'Add from', NULL, NULL),
    ('entity_add_from', 'label', 'et', 'string', 'Lisa menüüst/objektist', NULL, NULL),
    ('entity_add_from', 'type', NULL, 'string', 'reference', NULL, NULL),
    ('entity_add_from', 'ordinal', NULL, 'integer', NULL, 60, NULL),
    ('entity_add_from', 'list', NULL, 'boolean', NULL, 1, NULL),
    ('entity_add_from', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('entity_default_parent', '_mid', NULL, 'string', 'entity_default_parent', NULL, NULL),
    ('entity_default_parent', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('entity_default_parent', '_parent', NULL, 'reference', NULL, NULL, 'entity'),
    ('entity_default_parent', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('entity_default_parent', 'name', NULL, 'string', 'default_parent', NULL, NULL),
    ('entity_default_parent', 'label', 'en', 'string', 'Default parent', NULL, NULL),
    ('entity_default_parent', 'label', 'et', 'string', 'Lisa objekti alla', NULL, NULL),
    ('entity_default_parent', 'type', NULL, 'string', 'reference', NULL, NULL),
    ('entity_default_parent', 'ordinal', NULL, 'integer', NULL, 60, NULL),
    ('entity_default_parent', 'list', NULL, 'boolean', NULL, 1, NULL),
    ('entity_default_parent', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('entity_plugin', '_mid', NULL, 'string', 'entity_plugin', NULL, NULL),
    ('entity_plugin', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('entity_plugin', '_parent', NULL, 'reference', NULL, NULL, 'entity'),
    ('entity_plugin', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('entity_plugin', 'name', NULL, 'string', 'plugin', NULL, NULL),
    ('entity_plugin', 'label', 'en', 'string', 'Plugin', NULL, NULL),
    ('entity_plugin', 'label', 'et', 'string', 'Pistikprogramm', NULL, NULL),
    ('entity_plugin', 'type', NULL, 'string', 'reference', NULL, NULL),
    ('entity_plugin', 'reference_query', NULL, 'string', '_type.string=plugin&type.string.gte=entity-', NULL, NULL),
    ('entity_plugin', 'ordinal', NULL, 'integer', NULL, 65, NULL),
    ('entity_plugin', 'list', NULL, 'boolean', NULL, 1, NULL),
    ('entity_plugin', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property', '_mid', NULL, 'string', 'property', NULL, NULL),
    ('property', '_type', NULL, 'reference', NULL, NULL, 'entity'),
    ('property', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property', 'name', NULL, 'string', 'property', NULL, NULL),
    ('property', 'label', 'en', 'string', 'Property', NULL, NULL),
    ('property', 'label', 'et', 'string', 'Parameeter', NULL, NULL),
    ('property', 'label_plural', 'en', 'string', 'Properties', NULL, NULL),
    ('property', 'label_plural', 'et', 'string', 'Parameetrid', NULL, NULL),
    ('property', 'add_from', NULL, 'reference', NULL, NULL, 'entity'),
    ('property', 'system', NULL, 'boolean', NULL, 1, NULL),

    ('property_name', '_mid', NULL, 'string', 'property_name', NULL, NULL),
    ('property_name', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_name', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_name', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_name', 'name', NULL, 'string', 'name', NULL, NULL),
    ('property_name', 'label', 'en', 'string', 'Name', NULL, NULL),
    ('property_name', 'label', 'et', 'string', 'Nimi', NULL, NULL),
    ('property_name', 'type', NULL, 'string', 'string', NULL, NULL),
    ('property_name', 'ordinal', NULL, 'integer', NULL, 10, NULL),
    ('property_name', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('property_name', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('property_name', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('property_name', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_type', '_mid', NULL, 'string', 'property_type', NULL, NULL),
    ('property_type', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_type', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_type', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_type', 'name', NULL, 'string', 'type', NULL, NULL),
    ('property_type', 'label', 'en', 'string', 'Type', NULL, NULL),
    ('property_type', 'label', 'et', 'string', 'Tüüp', NULL, NULL),
    ('property_type', 'type', NULL, 'string', 'string', NULL, NULL),
    ('property_type', 'ordinal', NULL, 'integer', NULL, 15, NULL),
    ('property_type', 'set', NULL, 'string', 'boolean', NULL, NULL),
    ('property_type', 'set', NULL, 'string', 'counter', NULL, NULL),
    ('property_type', 'set', NULL, 'string', 'date', NULL, NULL),
    ('property_type', 'set', NULL, 'string', 'datetime', NULL, NULL),
    ('property_type', 'set', NULL, 'string', 'file', NULL, NULL),
    ('property_type', 'set', NULL, 'string', 'number', NULL, NULL),
    ('property_type', 'set', NULL, 'string', 'reference', NULL, NULL),
    ('property_type', 'set', NULL, 'string', 'set', NULL, NULL),
    ('property_type', 'set', NULL, 'string', 'string', NULL, NULL),
    ('property_type', 'set', NULL, 'string', 'text', NULL, NULL),
    ('property_type', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('property_type', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('property_type', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('property_type', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_label', '_mid', NULL, 'string', 'property_label', NULL, NULL),
    ('property_label', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_label', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_label', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_label', 'name', NULL, 'string', 'label', NULL, NULL),
    ('property_label', 'label', 'en', 'string', 'Label', NULL, NULL),
    ('property_label', 'label', 'et', 'string', 'Silt', NULL, NULL),
    ('property_label', 'type', NULL, 'string', 'string', NULL, NULL),
    ('property_label', 'ordinal', NULL, 'integer', NULL, 20, NULL),
    ('property_label', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('property_label', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('property_label', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('property_label', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('property_label', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_label_plural', '_mid', NULL, 'string', 'property_label_plural', NULL, NULL),
    ('property_label_plural', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_label_plural', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_label_plural', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_label_plural', 'name', NULL, 'string', 'label_plural', NULL, NULL),
    ('property_label_plural', 'label', 'en', 'string', 'Label (plural)', NULL, NULL),
    ('property_label_plural', 'label', 'et', 'string', 'Silt (mitmuses)', NULL, NULL),
    ('property_label_plural', 'type', NULL, 'string', 'string', NULL, NULL),
    ('property_label_plural', 'ordinal', NULL, 'integer', NULL, 30, NULL),
    ('property_label_plural', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('property_label_plural', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('property_label_plural', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_description', '_mid', NULL, 'string', 'property_description', NULL, NULL),
    ('property_description', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_description', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_description', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_description', 'name', NULL, 'string', 'description', NULL, NULL),
    ('property_description', 'label', 'en', 'string', 'Description (help text)', NULL, NULL),
    ('property_description', 'label', 'et', 'string', 'Kirjeldus (abi tekst)', NULL, NULL),
    ('property_description', 'type', NULL, 'string', 'text', NULL, NULL),
    ('property_description', 'ordinal', NULL, 'integer', NULL, 35, NULL),
    ('property_description', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('property_description', 'markdown', NULL, 'boolean', NULL, 1, NULL),
    ('property_description', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_group', '_mid', NULL, 'string', 'property_group', NULL, NULL),
    ('property_group', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_group', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_group', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_group', 'name', NULL, 'string', 'group', NULL, NULL),
    ('property_group', 'label', 'en', 'string', 'Group', NULL, NULL),
    ('property_group', 'label', 'et', 'string', 'Grupp', NULL, NULL),
    ('property_group', 'type', NULL, 'string', 'string', NULL, NULL),
    ('property_group', 'ordinal', NULL, 'integer', NULL, 40, NULL),
    ('property_group', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('property_group', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('property_group', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('property_group', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_ordinal', '_mid', NULL, 'string', 'property_ordinal', NULL, NULL),
    ('property_ordinal', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_ordinal', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_ordinal', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_ordinal', 'name', NULL, 'string', 'ordinal', NULL, NULL),
    ('property_ordinal', 'label', 'en', 'string', 'Ordinal', NULL, NULL),
    ('property_ordinal', 'label', 'et', 'string', 'Järjekord', NULL, NULL),
    ('property_ordinal', 'type', NULL, 'string', 'number', NULL, NULL),
    ('property_ordinal', 'ordinal', NULL, 'integer', NULL, 60, NULL),
    ('property_ordinal', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('property_ordinal', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_list', '_mid', NULL, 'string', 'property_list', NULL, NULL),
    ('property_list', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_list', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_list', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_list', 'name', NULL, 'string', 'list', NULL, NULL),
    ('property_list', 'label', 'en', 'string', 'Is list', NULL, NULL),
    ('property_list', 'label', 'et', 'string', 'On nimekiri', NULL, NULL),
    ('property_list', 'type', NULL, 'string', 'boolean', NULL, NULL),
    ('property_list', 'ordinal', NULL, 'integer', NULL, 70, NULL),
    ('property_list', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_markdown', '_mid', NULL, 'string', 'property_markdown', NULL, NULL),
    ('property_markdown', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_markdown', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_markdown', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_markdown', 'name', NULL, 'string', 'markdown', NULL, NULL),
    ('property_markdown', 'label', 'en', 'string', 'Is markdown', NULL, NULL),
    ('property_markdown', 'label', 'et', 'string', 'On markdown', NULL, NULL),
    ('property_markdown', 'type', NULL, 'string', 'boolean', NULL, NULL),
    ('property_markdown', 'ordinal', NULL, 'integer', NULL, 75, NULL),
    ('property_markdown', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_multilingual', '_mid', NULL, 'string', 'property_multilingual', NULL, NULL),
    ('property_multilingual', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_multilingual', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_multilingual', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_multilingual', 'name', NULL, 'string', 'multilingual', NULL, NULL),
    ('property_multilingual', 'label', 'en', 'string', 'Is multilingual', NULL, NULL),
    ('property_multilingual', 'label', 'et', 'string', 'On mitmekeelne', NULL, NULL),
    ('property_multilingual', 'type', NULL, 'string', 'boolean', NULL, NULL),
    ('property_multilingual', 'ordinal', NULL, 'integer', NULL, 80, NULL),
    ('property_multilingual', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_readonly', '_mid', NULL, 'string', 'property_readonly', NULL, NULL),
    ('property_readonly', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_readonly', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_readonly', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_readonly', 'name', NULL, 'string', 'readonly', NULL, NULL),
    ('property_readonly', 'label', 'en', 'string', 'Is read-only', NULL, NULL),
    ('property_readonly', 'label', 'et', 'string', 'On vaid loetav', NULL, NULL),
    ('property_readonly', 'type', NULL, 'string', 'boolean', NULL, NULL),
    ('property_readonly', 'ordinal', NULL, 'integer', NULL, 90, NULL),
    ('property_readonly', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_mandatory', '_mid', NULL, 'string', 'property_mandatory', NULL, NULL),
    ('property_mandatory', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_mandatory', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_mandatory', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_mandatory', 'name', NULL, 'string', 'mandatory', NULL, NULL),
    ('property_mandatory', 'label', 'en', 'string', 'Is mandatory', NULL, NULL),
    ('property_mandatory', 'label', 'et', 'string', 'On kohustuslik', NULL, NULL),
    ('property_mandatory', 'type', NULL, 'string', 'boolean', NULL, NULL),
    ('property_mandatory', 'ordinal', NULL, 'integer', NULL, 100, NULL),
    ('property_mandatory', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('property_mandatory', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_public', '_mid', NULL, 'string', 'property_public', NULL, NULL),
    ('property_public', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_public', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_public', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_public', 'name', NULL, 'string', 'public', NULL, NULL),
    ('property_public', 'label', 'en', 'string', 'Is public', NULL, NULL),
    ('property_public', 'label', 'et', 'string', 'On avalik', NULL, NULL),
    ('property_public', 'type', NULL, 'string', 'boolean', NULL, NULL),
    ('property_public', 'ordinal', NULL, 'integer', NULL, 110, NULL),
    ('property_public', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('property_public', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_search', '_mid', NULL, 'string', 'property_search', NULL, NULL),
    ('property_search', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_search', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_search', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_search', 'name', NULL, 'string', 'search', NULL, NULL),
    ('property_search', 'label', 'en', 'string', 'Is searchable', NULL, NULL),
    ('property_search', 'label', 'et', 'string', 'On otsitav', NULL, NULL),
    ('property_search', 'type', NULL, 'string', 'boolean', NULL, NULL),
    ('property_search', 'ordinal', NULL, 'integer', NULL, 120, NULL),
    ('property_search', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_table', '_mid', NULL, 'string', 'property_table', NULL, NULL),
    ('property_table', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_table', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_table', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_table', 'name', NULL, 'string', 'table', NULL, NULL),
    ('property_table', 'label', 'en', 'string', 'Is in table viev', NULL, NULL),
    ('property_table', 'label', 'et', 'string', 'On tabelvaates', NULL, NULL),
    ('property_table', 'type', NULL, 'string', 'boolean', NULL, NULL),
    ('property_table', 'ordinal', NULL, 'integer', NULL, 130, NULL),
    ('property_table', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_decimals', '_mid', NULL, 'string', 'property_decimals', NULL, NULL),
    ('property_decimals', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_decimals', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_decimals', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_decimals', 'name', NULL, 'string', 'decimals', NULL, NULL),
    ('property_decimals', 'label', 'en', 'string', 'Decimal places', NULL, NULL),
    ('property_decimals', 'label', 'et', 'string', 'Kümnendkohti', NULL, NULL),
    ('property_decimals', 'type', NULL, 'string', 'number', NULL, NULL),
    ('property_decimals', 'ordinal', NULL, 'integer', NULL, 140, NULL),
    ('property_decimals', 'decimals', NULL, 'integer', NULL, 0, NULL),
    ('property_decimals', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_formula', '_mid', NULL, 'string', 'property_formula', NULL, NULL),
    ('property_formula', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_formula', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_formula', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_formula', 'name', NULL, 'string', 'formula', NULL, NULL),
    ('property_formula', 'label', 'en', 'string', 'Formula', NULL, NULL),
    ('property_formula', 'label', 'et', 'string', 'Valem', NULL, NULL),
    ('property_formula', 'type', NULL, 'string', 'string', NULL, NULL),
    ('property_formula', 'ordinal', NULL, 'integer', NULL, 150, NULL),
    ('property_formula', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_reference_query', '_mid', NULL, 'string', 'property_reference_query', NULL, NULL),
    ('property_reference_query', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_reference_query', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_reference_query', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_reference_query', 'name', NULL, 'string', 'reference_query', NULL, NULL),
    ('property_reference_query', 'label', 'en', 'string', 'Reference query', NULL, NULL),
    ('property_reference_query', 'label', 'et', 'string', 'Viidatavate päring', NULL, NULL),
    ('property_reference_query', 'type', NULL, 'string', 'string', NULL, NULL),
    ('property_reference_query', 'ordinal', NULL, 'integer', NULL, 160, NULL),
    ('property_reference_query', 'description', 'en', 'string', 'Entu API query to find the objects that can be referenced in this parameter. For example "_type.string=person&sort=name.string"', NULL, NULL),
    ('property_reference_query', 'description', 'et', 'string', 'Entu API päring objektide leidmiseks, millele saab selles parameetris viidata. Näiteks "_type.string=person&sort=name.string"', NULL, NULL),
    ('property_reference_query', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_set', '_mid', NULL, 'string', 'property_set', NULL, NULL),
    ('property_set', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_set', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_set', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_set', 'name', NULL, 'string', 'set', NULL, NULL),
    ('property_set', 'label', 'en', 'string', 'Set', NULL, NULL),
    ('property_set', 'label', 'et', 'string', 'Hulk', NULL, NULL),
    ('property_set', 'type', NULL, 'string', 'string', NULL, NULL),
    ('property_set', 'ordinal', NULL, 'integer', NULL, 170, NULL),
    ('property_set', 'list', NULL, 'boolean', NULL, 1, NULL),
    ('property_set', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('property_plugin', '_mid', NULL, 'string', 'property_plugin', NULL, NULL),
    ('property_plugin', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('property_plugin', '_parent', NULL, 'reference', NULL, NULL, 'property'),
    ('property_plugin', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('property_plugin', 'name', NULL, 'string', 'plugin', NULL, NULL),
    ('property_plugin', 'label', 'en', 'string', 'Plugin', NULL, NULL),
    ('property_plugin', 'label', 'et', 'string', 'Pistikprogramm', NULL, NULL),
    ('property_plugin', 'type', NULL, 'string', 'reference', NULL, NULL),
    ('property_plugin', 'reference_query', NULL, 'string', '_type.string=plugin&type.string.gte=property-', NULL, NULL),
    ('property_plugin', 'ordinal', NULL, 'integer', NULL, 180, NULL),
    ('property_plugin', 'list', NULL, 'boolean', NULL, 1, NULL),
    ('property_plugin', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('menu', '_mid', NULL, 'string', 'menu', NULL, NULL),
    ('menu', '_type', NULL, 'reference', NULL, NULL, 'entity'),
    ('menu', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('menu', 'name', NULL, 'string', 'menu', NULL, NULL),
    ('menu', 'label', 'en', 'string', 'Menu', NULL, NULL),
    ('menu', 'label', 'et', 'string', 'Menüü', NULL, NULL),
    ('menu', 'label_plural', 'en', 'string', 'Menus', NULL, NULL),
    ('menu', 'label_plural', 'et', 'string', 'Menüüd', NULL, NULL),
    ('menu', 'add_from', NULL, 'reference', NULL, NULL, 'menu_conf_menu'),
    ('menu', 'default_parent', NULL, 'reference', NULL, NULL, CONCAT('database_entity_', ?)),
    ('menu', 'system', NULL, 'boolean', NULL, 1, NULL),

    ('menu_name', '_mid', NULL, 'string', 'menu_name', NULL, NULL),
    ('menu_name', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('menu_name', '_parent', NULL, 'reference', NULL, NULL, 'menu'),
    ('menu_name', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('menu_name', 'name', NULL, 'string', 'name', NULL, NULL),
    ('menu_name', 'label', 'en', 'string', 'Name', NULL, NULL),
    ('menu_name', 'label', 'et', 'string', 'Nimi', NULL, NULL),
    ('menu_name', 'type', NULL, 'string', 'string', NULL, NULL),
    ('menu_name', 'ordinal', NULL, 'integer', NULL, 1, NULL),
    ('menu_name', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('menu_name', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('menu_name', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('menu_name', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('menu_name', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('menu_group', '_mid', NULL, 'string', 'menu_group', NULL, NULL),
    ('menu_group', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('menu_group', '_parent', NULL, 'reference', NULL, NULL, 'menu'),
    ('menu_group', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('menu_group', 'name', NULL, 'string', 'group', NULL, NULL),
    ('menu_group', 'label', 'en', 'string', 'Group', NULL, NULL),
    ('menu_group', 'label', 'et', 'string', 'Grupp', NULL, NULL),
    ('menu_group', 'type', NULL, 'string', 'string', NULL, NULL),
    ('menu_group', 'ordinal', NULL, 'integer', NULL, 2, NULL),
    ('menu_group', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('menu_group', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('menu_group', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('menu_group', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('menu_group', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('menu_ordinal', '_mid', NULL, 'string', 'menu_ordinal', NULL, NULL),
    ('menu_ordinal', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('menu_ordinal', '_parent', NULL, 'reference', NULL, NULL, 'menu'),
    ('menu_ordinal', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('menu_ordinal', 'name', NULL, 'string', 'ordinal', NULL, NULL),
    ('menu_ordinal', 'label', 'en', 'string', 'Ordinal', NULL, NULL),
    ('menu_ordinal', 'label', 'et', 'string', 'Järjekord', NULL, NULL),
    ('menu_ordinal', 'type', NULL, 'string', 'number', NULL, NULL),
    ('menu_ordinal', 'ordinal', NULL, 'integer', NULL, 3, NULL),
    ('menu_ordinal', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('menu_ordinal', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('menu_query', '_mid', NULL, 'string', 'menu_query', NULL, NULL),
    ('menu_query', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('menu_query', '_parent', NULL, 'reference', NULL, NULL, 'menu'),
    ('menu_query', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('menu_query', 'name', NULL, 'string', 'query', NULL, NULL),
    ('menu_query', 'label', 'en', 'string', 'Query', NULL, NULL),
    ('menu_query', 'label', 'et', 'string', 'Päring', NULL, NULL),
    ('menu_query', 'type', NULL, 'string', 'string', NULL, NULL),
    ('menu_query', 'ordinal', NULL, 'integer', NULL, 4, NULL),
    ('menu_query', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('menu_query', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('menu_query', 'description', 'en', 'string', 'Entu API query. For example "_type.string=person&sort=name.string"', NULL, NULL),
    ('menu_query', 'description', 'et', 'string', 'Entu API päring. Näiteks "_type.string=person&sort=name.string"', NULL, NULL),
    ('menu_query', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('menu_query', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('menu_description', '_mid', NULL, 'string', 'menu_description', NULL, NULL),
    ('menu_description', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('menu_description', '_parent', NULL, 'reference', NULL, NULL, 'menu'),
    ('menu_description', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('menu_description', 'name', NULL, 'string', 'text', NULL, NULL),
    ('menu_description', 'label', 'en', 'string', 'Description', NULL, NULL),
    ('menu_description', 'label', 'et', 'string', 'Kirjeldus', NULL, NULL),
    ('menu_description', 'type', NULL, 'string', 'text', NULL, NULL),
    ('menu_description', 'ordinal', NULL, 'integer', NULL, 5, NULL),
    ('menu_description', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('menu_description', 'markdown', NULL, 'boolean', NULL, 1, NULL),
    ('menu_description', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('plugin', '_mid', NULL, 'string', 'plugin', NULL, NULL),
    ('plugin', '_type', NULL, 'reference', NULL, NULL, 'entity'),
    ('plugin', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('plugin', 'name', NULL, 'string', 'plugin', NULL, NULL),
    ('plugin', 'label', 'en', 'string', 'Plugin', NULL, NULL),
    ('plugin', 'label', 'et', 'string', 'Pistikprogramm', NULL, NULL),
    ('plugin', 'label_plural', 'en', 'string', 'Plugins', NULL, NULL),
    ('plugin', 'label_plural', 'et', 'string', 'Pistikprogrammid', NULL, NULL),
    ('plugin', 'add_from', NULL, 'reference', NULL, NULL, 'menu_conf_plugin'),
    ('plugin', 'default_parent', NULL, 'reference', NULL, NULL, CONCAT('database_entity_', ?)),
    ('plugin', 'system', NULL, 'boolean', NULL, 1, NULL),

    ('plugin_name', '_mid', NULL, 'string', 'plugin_name', NULL, NULL),
    ('plugin_name', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('plugin_name', '_parent', NULL, 'reference', NULL, NULL, 'plugin'),
    ('plugin_name', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('plugin_name', 'name', NULL, 'string', 'name', NULL, NULL),
    ('plugin_name', 'label', 'en', 'string', 'Name', NULL, NULL),
    ('plugin_name', 'label', 'et', 'string', 'Nimi', NULL, NULL),
    ('plugin_name', 'type', NULL, 'string', 'string', NULL, NULL),
    ('plugin_name', 'ordinal', NULL, 'integer', NULL, 1, NULL),
    ('plugin_name', 'multilingual', NULL, 'boolean', NULL, 1, NULL),
    ('plugin_name', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('plugin_name', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('plugin_name', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('plugin_name', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('plugin_type', '_mid', NULL, 'string', 'plugin_type', NULL, NULL),
    ('plugin_type', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('plugin_type', '_parent', NULL, 'reference', NULL, NULL, 'plugin'),
    ('plugin_type', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('plugin_type', 'name', NULL, 'string', 'type', NULL, NULL),
    ('plugin_type', 'label', 'en', 'string', 'Type', NULL, NULL),
    ('plugin_type', 'label', 'et', 'string', 'Tüüp', NULL, NULL),
    ('plugin_type', 'type', NULL, 'string', 'string', NULL, NULL),
    ('plugin_type', 'ordinal', NULL, 'integer', NULL, 15, NULL),
    ('plugin_type', 'set', NULL, 'string', 'entity-add', NULL, NULL),
    ('plugin_type', 'set', NULL, 'string', 'entity-edit', NULL, NULL),
    ('plugin_type', 'set', NULL, 'string', 'entity-view', NULL, NULL),
    ('plugin_type', 'set', NULL, 'string', 'property-add', NULL, NULL),
    ('plugin_type', 'set', NULL, 'string', 'property-edit', NULL, NULL),
    ('plugin_type', 'set', NULL, 'string', 'property-view', NULL, NULL),
    ('plugin_type', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('plugin_type', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('plugin_type', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('plugin_type', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('plugin_url', '_mid', NULL, 'string', 'plugin_url', NULL, NULL),
    ('plugin_url', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('plugin_url', '_parent', NULL, 'reference', NULL, NULL, 'plugin'),
    ('plugin_url', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('plugin_url', 'name', NULL, 'string', 'url', NULL, NULL),
    ('plugin_url', 'label', 'en', 'string', 'URL', NULL, NULL),
    ('plugin_url', 'label', 'et', 'string', 'URL', NULL, NULL),
    ('plugin_url', 'type', NULL, 'string', 'string', NULL, NULL),
    ('plugin_url', 'ordinal', NULL, 'integer', NULL, 20, NULL),
    ('plugin_url', 'search', NULL, 'boolean', NULL, 1, NULL),
    ('plugin_url', 'mandatory', NULL, 'boolean', NULL, 1, NULL),
    ('plugin_url', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('plugin_url', 'public', NULL, 'boolean', NULL, 1, NULL),

    ('plugin_new_window', '_mid', NULL, 'string', 'plugin_new_window', NULL, NULL),
    ('plugin_new_window', '_type', NULL, 'reference', NULL, NULL, 'property'),
    ('plugin_new_window', '_parent', NULL, 'reference', NULL, NULL, 'plugin'),
    ('plugin_new_window', '_sharing', NULL, 'string', 'domain', NULL, NULL),
    ('plugin_new_window', 'name', NULL, 'string', 'new_window', NULL, NULL),
    ('plugin_new_window', 'label', 'en', 'string', 'Open in new window', NULL, NULL),
    ('plugin_new_window', 'label', 'et', 'string', 'Ava uues aknas', NULL, NULL),
    ('plugin_new_window', 'type', NULL, 'string', 'boolean', NULL, NULL),
    ('plugin_new_window', 'ordinal', NULL, 'integer', NULL, 25, NULL),
    ('plugin_new_window', 'table', NULL, 'boolean', NULL, 1, NULL),
    ('plugin_new_window', 'public', NULL, 'boolean', NULL, 1, NULL);
